---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "covid-data-fetching"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "covid-data-fetching"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  name: "covid-data-fetching"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "covid-data-fetching"
      app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
        app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
        app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
      labels:
        app.kubernetes.io/name: "covid-data-fetching"
        app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "olirajun/covid-data-fetching:1.0.0-SNAPSHOT"
        imagePullPolicy: "Always"
        name: "covid-data-fetching"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "covid-data-fetching"
