---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "covid-data-fetching"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "covid-data-fetching"
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "image.openshift.io/v1"
kind: "ImageStream"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "covid-data-fetching"
spec: {}
---
apiVersion: "image.openshift.io/v1"
kind: "ImageStream"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "s2i-java"
spec:
  dockerImageRepository: "fabric8/s2i-java"
---
apiVersion: "image.openshift.io/v1"
kind: "ImageStream"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "s2i-java"
spec:
  dockerImageRepository: "fabric8/s2i-java"
---
apiVersion: "build.openshift.io/v1"
kind: "BuildConfig"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "covid-data-fetching"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "covid-data-fetching:1.0.0-SNAPSHOT"
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "s2i-java:latest-java11"
---
apiVersion: "apps.openshift.io/v1"
kind: "DeploymentConfig"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
    app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
    app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
    app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
  labels:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
    app.openshift.io/runtime: "quarkus"
  name: "covid-data-fetching"
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: "covid-data-fetching"
    app.kubernetes.io/version: "1.0.0-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: "2020-06-19 - 16:18:03 +0000"
        app.openshift.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
        app.quarkus.io/commit-id: "4703c4f408d42000dd4159ecb01430547bcffb5a"
        app.quarkus.io/vcs-url: "https://github.com/gmccarth/covid-data-fetching.git"
      labels:
        app.kubernetes.io/name: "covid-data-fetching"
        app.kubernetes.io/version: "1.0.0-SNAPSHOT"
        app.openshift.io/runtime: "quarkus"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "JAVA_APP_JAR"
          value: "/deployments/covid-data-fetching-1.0.0-SNAPSHOT-runner.jar"
        - name: "JAVA_LIB_DIR"
          value: "/deployments/lib"
        - name: "JAVA_CLASSPATH"
          value: "/deployments/lib/io.smallrye.reactive.mutiny-0.4.4.jar:/deployments/lib/io.quarkus.security.quarkus-security-1.1.0.Final.jar:/deployments/lib/jakarta.el.jakarta.el-api-3.0.3.jar:/deployments/lib/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:/deployments/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:/deployments/lib/io.netty.netty-common-4.1.45.Final.jar:/deployments/lib/io.netty.netty-buffer-4.1.45.Final.jar:/deployments/lib/io.netty.netty-transport-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-socks-4.1.45.Final.jar:/deployments/lib/io.netty.netty-handler-proxy-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-http-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-http2-4.1.45.Final.jar:/deployments/lib/io.netty.netty-resolver-4.1.45.Final.jar:/deployments/lib/io.netty.netty-codec-dns-4.1.45.Final.jar:/deployments/lib/io.netty.netty-resolver-dns-4.1.45.Final.jar:/deployments/lib/io.vertx.vertx-core-3.8.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-core-1.4.2.Final.jar:/deployments/lib/io.vertx.vertx-web-common-3.8.5.jar:/deployments/lib/io.vertx.vertx-auth-common-3.8.5.jar:/deployments/lib/io.vertx.vertx-bridge-common-3.8.5.jar:/deployments/lib/io.vertx.vertx-web-3.8.5.jar:/deployments/lib/io.quarkus.quarkus-vertx-http-1.4.2.Final.jar:/deployments/lib/org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-spi-4.5.3.Final.jar:/deployments/lib/org.jboss.resteasy.resteasy-core-4.5.3.Final.jar:/deployments/lib/com.sun.activation.jakarta.activation-1.2.1.jar:/deployments/lib/io.quarkus.quarkus-resteasy-common-1.4.2.Final.jar:/deployments/lib/jakarta.validation.jakarta.validation-api-2.0.2.jar:/deployments/lib/io.quarkus.quarkus-resteasy-server-common-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-resteasy-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-kubernetes-client-internal-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-openshift-1.4.2.Final.jar:/deployments/lib/org.apache.camel.camel-support-3.2.0.jar:/deployments/lib/org.apache.camel.camel-timer-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-timer-1.0.0-M7.jar:/deployments/lib/com.ibm.icu.icu4j-65.1.jar:/deployments/lib/org.apache.camel.camel-bindy-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-bindy-1.0.0-M7.jar:/deployments/lib/org.apache.commons.commons-csv-1.6.jar:/deployments/lib/org.apache.camel.camel-csv-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-csv-1.0.0-M7.jar:/deployments/lib/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:/deployments/lib/jakarta.inject.jakarta.inject-api-1.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-common-1.7.0.jar:/deployments/lib/io.smallrye.config.smallrye-config-1.7.0.jar:/deployments/lib/org.jboss.logging.jboss-logging-3.3.2.Final.jar:/deployments/lib/org.jboss.logmanager.jboss-logmanager-embedded-1.0.4.jar:/deployments/lib/org.jboss.logging.jboss-logging-annotations-2.1.0.Final.jar:/deployments/lib/org.jboss.threads.jboss-threads-3.1.1.Final.jar:/deployments/lib/org.slf4j.slf4j-api-1.7.30.jar:/deployments/lib/org.jboss.slf4j.slf4j-jboss-logging-1.2.0.Final.jar:/deployments/lib/org.graalvm.sdk.graal-sdk-19.3.1.jar:/deployments/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/deployments/lib/io.quarkus.quarkus-core-1.4.2.Final.jar:/deployments/lib/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:/deployments/lib/io.quarkus.arc.arc-1.4.2.Final.jar:/deployments/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.0.1.jar:/deployments/lib/io.quarkus.quarkus-arc-1.4.2.Final.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-support-common-1.0.0-M7.jar:/deployments/lib/io.quarkus.quarkus-development-mode-spi-1.4.2.Final.jar:/deployments/lib/org.apache.camel.camel-api-3.2.0.jar:/deployments/lib/org.apache.camel.camel-management-api-3.2.0.jar:/deployments/lib/org.apache.camel.camel-util-3.2.0.jar:/deployments/lib/org.apache.camel.camel-main-3.2.0.jar:/deployments/lib/org.apache.camel.camel-core-engine-3.2.0.jar:/deployments/lib/org.apache.camel.camel-base-3.2.0.jar:/deployments/lib/org.apache.camel.camel-core-languages-3.2.0.jar:/deployments/lib/org.apache.camel.camel-endpointdsl-3.2.0.jar:/deployments/lib/org.apache.camel.camel-componentdsl-3.2.0.jar:/deployments/lib/org.apache.camel.camel-util-json-3.2.0.jar:/deployments/lib/org.apache.camel.camel-tooling-model-3.2.0.jar:/deployments/lib/org.apache.camel.camel-core-catalog-3.2.0.jar:/deployments/lib/org.eclipse.microprofile.config.microprofile-config-api-1.4.jar:/deployments/lib/org.apache.camel.camel-microprofile-config-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-core-1.0.0-M7.jar:/deployments/lib/org.apache.camel.camel-kafka-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-kafka-1.0.0-M7.jar:/deployments/lib/com.github.luben.zstd-jni-1.4.3-1.jar:/deployments/lib/org.lz4.lz4-java-1.6.0.jar:/deployments/lib/org.xerial.snappy.snappy-java-1.1.7.3.jar:/deployments/lib/org.apache.kafka.kafka-clients-2.4.1.jar:/deployments/lib/io.quarkus.quarkus-kafka-client-1.4.2.Final.jar:/deployments/lib/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-api-1.0.1.jar:/deployments/lib/org.eclipse.microprofile.reactive-streams-operators.microprofile-reactive-streams-operators-core-1.0.1.jar:/deployments/lib/io.reactivex.rxjava2.rxjava-2.2.19.jar:/deployments/lib/io.smallrye.reactive.smallrye-reactive-streams-operators-1.0.10.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-propagators-rxjava2-1.0.11.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-api-1.0.11.jar:/deployments/lib/io.smallrye.smallrye-context-propagation-1.0.11.jar:/deployments/lib/io.quarkus.quarkus-smallrye-context-propagation-1.4.2.Final.jar:/deployments/lib/io.quarkus.quarkus-smallrye-reactive-streams-operators-1.4.2.Final.jar:/deployments/lib/io.netty.netty-codec-4.1.45.Final.jar:/deployments/lib/io.netty.netty-handler-4.1.45.Final.jar:/deployments/lib/io.quarkus.quarkus-netty-1.4.2.Final.jar:/deployments/lib/org.mvel.mvel2-2.4.7.Final.jar:/deployments/lib/io.vertx.vertx-codegen-3.8.5.jar:/deployments/lib/io.smallrye.reactive.smallrye-axle-generator-0.0.13.jar:/deployments/lib/io.smallrye.reactive.smallrye-axle-core-0.0.13.jar:/deployments/lib/io.vertx.vertx-rx-gen-3.8.5.jar:/deployments/lib/io.vertx.vertx-rx-java2-3.8.5.jar:/deployments/lib/io.smallrye.reactive.mutiny-context-propagation-0.4.4.jar:/deployments/lib/io.smallrye.reactive.smallrye-reactive-converter-api-1.0.10.jar:/deployments/lib/io.quarkus.quarkus-mutiny-1.4.2.Final.jar:/deployments/lib/io.smallrye.reactive.smallrye-mutiny-vertx-runtime-0.0.13.jar:/deployments/lib/io.smallrye.reactive.vertx-mutiny-generator-0.0.13.jar:/deployments/lib/io.smallrye.reactive.smallrye-mutiny-vertx-core-0.0.13.jar:/deployments/lib/io.quarkus.quarkus-vertx-1.4.2.Final.jar:/deployments/lib/org.mongodb.bson-4.0.0.jar:/deployments/lib/org.mongodb.mongodb-driver-core-4.0.0.jar:/deployments/lib/org.mongodb.mongodb-driver-sync-4.0.0.jar:/deployments/lib/org.reactivestreams.reactive-streams-1.0.3.jar:/deployments/lib/org.mongodb.mongodb-driver-reactivestreams-4.0.0.jar:/deployments/lib/net.java.dev.jna.jna-5.3.1.jar:/deployments/lib/org.mongodb.mongodb-crypt-1.0.0.jar:/deployments/lib/io.quarkus.quarkus-mongodb-client-1.4.2.Final.jar:/deployments/lib/org.apache.camel.camel-mongodb-3.2.0.jar:/deployments/lib/org.mongodb.mongodb-driver-legacy-4.0.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-mongodb-1.0.0-M7.jar:/deployments/lib/com.sun.xml.bind.jaxb-core-2.3.0.jar:/deployments/lib/com.sun.xml.bind.jaxb-impl-2.3.0.jar:/deployments/lib/org.apache.camel.camel-xml-jaxp-3.2.0.jar:/deployments/lib/org.apache.camel.camel-xml-jaxb-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-support-xml-1.0.0-M7.jar:/deployments/lib/org.glassfish.jaxb.txw2-2.3.3-b02.jar:/deployments/lib/com.sun.istack.istack-commons-runtime-3.0.10.jar:/deployments/lib/org.glassfish.jaxb.jaxb-runtime-2.3.3-b02.jar:/deployments/lib/io.quarkus.quarkus-jaxb-1.4.2.Final.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-xml-jaxb-1.0.0-M7.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-databind-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.module.jackson-module-parameter-names-2.10.3.jar:/deployments/lib/io.quarkus.quarkus-jackson-1.4.2.Final.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-annotations-2.10.3.jar:/deployments/lib/com.fasterxml.jackson.core.jackson-core-2.10.3.jar:/deployments/lib/jakarta.activation.jakarta.activation-api-1.2.1.jar:/deployments/lib/com.fasterxml.jackson.module.jackson-module-jaxb-annotations-2.10.3.jar:/deployments/lib/org.apache.camel.camel-jackson-3.2.0.jar:/deployments/lib/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-jackson-1.0.0-M7.jar:/deployments/lib/org.apache.camel.camel-http-base-3.2.0.jar:/deployments/lib/com.sun.activation.javax.activation-1.2.0.jar:/deployments/lib/org.apache.camel.camel-attachments-3.2.0.jar:/deployments/lib/org.apache.camel.camel-http-common-3.2.0.jar:/deployments/lib/jakarta.servlet.jakarta.servlet-api-4.0.3.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-http-common-1.0.0-M7.jar:/deployments/lib/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-support-commons-logging-1.0.0-M7.jar:/deployments/lib/org.apache.httpcomponents.httpcore-4.4.13.jar:/deployments/lib/commons-codec.commons-codec-1.13.jar:/deployments/lib/org.apache.httpcomponents.httpclient-4.5.12.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-support-httpclient-1.0.0-M7.jar:/deployments/lib/org.apache.camel.camel-cloud-3.2.0.jar:/deployments/lib/org.apache.camel.camel-cluster-3.2.0.jar:/deployments/lib/org.apache.camel.camel-file-3.2.0.jar:/deployments/lib/org.apache.camel.camel-http-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-http-1.0.0-M7.jar:/deployments/lib/org.apache.camel.camel-bean-3.2.0.jar:/deployments/lib/org.apache.camel.quarkus.camel-quarkus-bean-1.0.0-M7.jar:/deployments/lib/org.json.json-20190722.jar"
        - name: "JAVA_OPTIONS"
          value: "-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
        image: "olirajun/covid-data-fetching:1.0.0-SNAPSHOT"
        imagePullPolicy: "Always"
        name: "covid-data-fetching"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "covid-data-fetching"
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - "covid-data-fetching"
      from:
        kind: "ImageStreamTag"
        name: "covid-data-fetching:1.0.0-SNAPSHOT"
    type: "ImageChange"
